name: 打包
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: 安装依赖
        run: |
          pip install pyinstaller==6.3.0
          pip install pyautogui==0.9.53 pillow==10.2.0 numpy==1.25.2 keyboard==0.13.5
        shell: pwsh
      - name: 打包
        run: |
          pyinstaller --onefile --windowed --noupx --name="DesktopAutoClicker" auto_clicker.py
        shell: pwsh
      - name: 上传Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          files: dist/DesktopAutoClicker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
